"""Build Word documents from POST /query-shaped analysis JSON."""

from __future__ import annotations

import json
import re
from datetime import date
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parent.parent
REPORTS_DIR = ROOT / "atlas_vault" / "03-Outputs" / "Reports"


def _txt(value: Any, limit: int = 8000) -> str:
    if value is None:
        return ""
    if isinstance(value, (dict, list)):
        try:
            text = json.dumps(value, indent=2, default=str)
        except (TypeError, ValueError):
            text = str(value)
    else:
        text = str(value).strip()
    return text[:limit].strip()


def _slug(envelope: dict[str, Any]) -> str:
    pq = envelope.get("parsed_query") if isinstance(envelope.get("parsed_query"), dict) else {}
    fr = envelope.get("final_report") if isinstance(envelope.get("final_report"), dict) else {}
    tickers = pq.get("tickers")
    ticker = tickers[0] if isinstance(tickers, list) and tickers else ""
    raw = fr.get("company_name") or fr.get("ticker") or ticker
    if not raw:
        raw = envelope.get("query") or "ra_omega_report"
    slug = re.sub(r"[^\w\-]+", "_", str(raw).strip())[:48].strip("_")
    return slug or "ra_omega_report"


def _section_items(envelope: dict[str, Any]) -> list[tuple[str, Any]]:
    fr = envelope.get("final_report") if isinstance(envelope.get("final_report"), dict) else {}
    sections: list[tuple[str, Any]] = [
        ("Bottom Line", envelope.get("tldr") or fr.get("tldr") or fr.get("bottom_line")),
        ("Executive Summary", fr.get("executive_summary") or fr.get("executive_brief")),
        ("Company Overview", fr.get("company_overview") or fr.get("overview") or fr.get("what_they_do")),
        ("Business Model", fr.get("business_model")),
        ("Financial Snapshot", fr.get("financial_snapshot") or fr.get("numbers_that_matter")),
        ("Recent News / Catalysts", fr.get("recent_news") or fr.get("catalysts_timeline")),
        ("Competitive Position", fr.get("competitive_position")),
        ("Key Risks", fr.get("key_risks") or fr.get("risks_and_tripwires")),
        ("Scenarios", envelope.get("scenarios") or fr.get("scenarios")),
        ("Sources / Data Notes", fr.get("sources") or fr.get("data_notes") or fr.get("named_resources")),
    ]
    if envelope.get("_output_mode") == "trade_plan":
        sections.extend(
            [
                ("Trade Plan", fr.get("trade_plan")),
                ("Execution Rules", envelope.get("execution_rules") or fr.get("execution_rules")),
            ]
        )
    return [(title, value) for title, value in sections if _txt(value)]


def write_query_envelope_docx(
    envelope: dict[str, Any],
    dest: Path | None = None,
) -> Path:
    """Write a Word document and return its path."""
    from docx import Document
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.shared import Pt

    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    target = dest or (REPORTS_DIR / f"{_slug(envelope)}_{date.today().strftime('%Y-%m-%d')}.docx")

    fr = envelope.get("final_report") if isinstance(envelope.get("final_report"), dict) else {}
    title = (
        fr.get("title")
        or fr.get("headline")
        or fr.get("company_name")
        or envelope.get("query")
        or "R.A. Omega Intelligence Report"
    )

    doc = Document()
    styles = doc.styles
    styles["Normal"].font.name = "Arial"
    styles["Normal"].font.size = Pt(10.5)

    heading = doc.add_heading(_txt(title, 180), level=0)
    heading.alignment = WD_ALIGN_PARAGRAPH.CENTER
    meta = doc.add_paragraph(f"Generated by R.A. Omega | {date.today().isoformat()}")
    meta.alignment = WD_ALIGN_PARAGRAPH.CENTER

    query = _txt(envelope.get("query"), 600)
    if query:
        doc.add_heading("Request", level=1)
        doc.add_paragraph(query)

    for title, value in _section_items(envelope):
        doc.add_heading(title, level=1)
        if isinstance(value, list):
            for item in value[:12]:
                doc.add_paragraph(_txt(item, 1200), style="List Bullet")
        elif isinstance(value, dict):
            for key, val in list(value.items())[:20]:
                text = _txt(val, 1200)
                if text:
                    doc.add_paragraph(f"{str(key).replace('_', ' ').title()}: {text}", style="List Bullet")
        else:
            doc.add_paragraph(_txt(value, 8000))

    doc.add_paragraph(
        "R.A. Omega synthesizes available data for research purposes. This is not personalized investment advice."
    )
    doc.save(target)
    return target
